language: php

php:
- 5.5

env:
  global:
    - APP_ENV=local
    - APP_DEBUG=true
    - APP_KEY=wolWin0qMnq1SGBrpwbPhHnz1qO4yh1o

    - DB_HOST=127.0.0.1
    - DB_DATABASE=authtodo
    - DB_USERNAME=travis

    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer require satooshi/php-coveralls
  - mysql -e 'create database authtodo;'
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls