language: php

php:
- 5.5

env:
  global:
    - APP_ENV=local
    - APP_DEBUG=true
    - APP_KEY=wolWin0qMnq1SGBrpwbPhHnz1qO4yh1o

    - DB_HOST=127.0.0.1
    - DB_DATABASE=authtodo
    - DB_USERNAME=travis

    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

    - MAIL_DRIVER=smtp
    - MAIL_HOST=mailtrap.io
    - MAIL_PORT=25
    - MAIL_ADDRESS=from@example.com
    - MAIL_NAME=mailtrap.io
    - MAIL_USERNAME=5472474fab90ba6bc
    - MAIL_PASSWORD=acf6d01b20bb28
    - MAIL_ENCRYPTION=null

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer require satooshi/php-coveralls
  - mysql -e 'create database authtodo;'
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls