<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class UserTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testExample()
    {
        //test the unauthentication first to avoid the token generated by next assert
        $this->get('/api/authenticate/user')
            ->donSeeJsonKey('user')
            ->see('token_not_provided');

        $this->authUserGet('/api/authenticate/user')
            ->seeJsonKey('user')
            ->seeJsonKey('email');
    }
}